
name: AdminTroll
main: Swourire\AdminTroll\Main
version: 1.2.0
api: 3.0.0

author: Swourire
commands:
 admintroll:
  description:  Admin Troll on/off.
  usage: "Type /admintroll with nothing after, it'll give you the inventory"
  permission: AdminTroll.perm
  default: false
 troll:
  description: Invoke a troll

 
