
name: AdminTroll
main: Swourire\AdminTroll\Main
version: 1.0.0
api: 3.2.0

author: Swourire
commands:
 admintroll:
  description:  Admin Troll on/off.
  usage: "/admintroll"
  permission: AdminTroll.perm
  default: false

 